import type { MemeTicker } from "./types"

export const initialMemes: MemeTicker[] = [
  {
    id: "1",
    ticker: "TROLL",
    title: "Trollface",
    imageUrl: "/assets/memes/trollface.jpg",
    price: 420.69,
    percentChange: 69.42,
    volume: 8008135,
    timestamp: Date.now(),
  },
  {
    id: "2",
    ticker: "DICAP",
    title: "Leonardo DiCaprio Laughing",
    imageUrl: "/assets/memes/leonardo dicaprio laughing.jpg",
    price: 69.42,
    percentChange: -4.2,
    volume: 1337420,
    timestamp: Date.now(),
  },
  {
    id: "3",
    ticker: "WOJAK",
    title: "Wojak",
    imageUrl: "/assets/memes/wojak.jpg",
    price: 0.01,
    percentChange: 1000.0,
    volume: 9000001,
    timestamp: Date.now(),
  },
  {
    id: "4",
    ticker: "PABLO",
    title: "Sad Pablo",
    imageUrl: "/assets/memes/sad pablo.jpg",
    price: 0.5,
    percentChange: -99.9,
    volume: 1234567,
    timestamp: Date.now(),
  },
  {
    id: "5",
    ticker: "PEPE",
    title: "Pepe The Frog",
    imageUrl: "/assets/memes/pepe the frog.jpg",
    price: 1337.0,
    percentChange: 13.37,
    volume: 4206969,
    timestamp: Date.now(),
  },
  {
    id: "6",
    ticker: "FWP",
    title: "First World Problems",
    imageUrl: "/assets/memes/first world problems.jpg",
    price: 20.0,
    percentChange: 5.0,
    volume: 8675309,
    timestamp: Date.now(),
  },
  {
    id: "7",
    ticker: "GIGA",
    title: "Giga Chad",
    imageUrl: "/assets/memes/giga cahd.jpg",
    price: 999.99,
    percentChange: 42.0,
    volume: 6942069,
    timestamp: Date.now(),
  },
  {
    id: "8",
    ticker: "HPAIN",
    title: "Hide The Pain Harold",
    imageUrl: "/assets/memes/hide the pain harold.jpg",
    price: 34.95,
    percentChange: -2.5,
    volume: 5318008,
    timestamp: Date.now(),
  },
  {
    id: "9",
    ticker: "PIKA",
    title: "Surprised Pikachu",
    imageUrl: "/assets/memes/surprised pikachu.jpg",
    price: 80.08,
    percentChange: 8.008,
    volume: 8008135,
    timestamp: Date.now(),
  },
  {
    id: "10",
    ticker: "DOGE",
    title: "Doge",
    imageUrl: "/assets/memes/doge.jpg",
    price: 0.42069,
    percentChange: -12.34,
    volume: 1234321,
    timestamp: Date.now(),
  },
  {
    id: "11",
    ticker: "ALIEN",
    title: "Ancient Aliens Guy",
    imageUrl: "/assets/memes/ancient aliens guy.jpg",
    price: 4.0,
    percentChange: 0.01,
    volume: 4004004,
    timestamp: Date.now(),
  },
  {
    id: "12",
    ticker: "STONK",
    title: "Stonks",
    imageUrl: "/assets/memes/stonks.jpg",
    price: 1000000.0,
    percentChange: 100.0,
    volume: 9999999,
    timestamp: Date.now(),
  },
  {
    id: "13",
    ticker: "FINE",
    title: "This Is Fine",
    imageUrl: "/assets/memes/this is fine.jpg",
    price: 42.0,
    percentChange: -42.0,
    volume: 3141592,
    timestamp: Date.now(),
  },
  {
    id: "14",
    ticker: "DISTBF",
    title: "Distracted Boyfriend",
    imageUrl: "/assets/memes/distracted boyfriend.jpg",
    price: 69.0,
    percentChange: 4.20,
    volume: 8675309,
    timestamp: Date.now(),
  },
  {
    id: "15",
    ticker: "CATW",
    title: "Woman Yelling At Cat",
    imageUrl: "/assets/memes/woman yelling at cat.jpg",
    price: 88.88,
    percentChange: 8.8,
    volume: 7654321,
    timestamp: Date.now(),
  },
  {
    id: "16",
    ticker: "BLING",
    title: "Hotline Bling",
    imageUrl: "/assets/memes/hotline bling.jpg",
    price: 150.0,
    percentChange: 15.0,
    volume: 5555555,
    timestamp: Date.now(),
  },
  {
    id: "17",
    ticker: "NUMA",
    title: "Numa Numa",
    imageUrl: "/assets/memes/numa numa.jpg",
    price: 25.0,
    percentChange: 2.5,
    volume: 2222222,
    timestamp: Date.now(),
  },
  {
    id: "18",
    ticker: "SWK",
    title: "Star Wars Kid",
    imageUrl: "/assets/memes/star wars kid.jpg",
    price: 35.0,
    percentChange: 3.5,
    volume: 3333333,
    timestamp: Date.now(),
  },
  {
    id: "19",
    ticker: "CMM",
    title: "Change My Mind",
    imageUrl: "/assets/memes/change my mind.jpg",
    price: 120.0,
    percentChange: 12.0,
    volume: 4444444,
    timestamp: Date.now(),
  },
  {
    id: "20",
    ticker: "SPNGE",
    title: "Mocking Spongebob",
    imageUrl: "/assets/memes/Mocking-Spongebob.jpg",
    price: 250.0,
    percentChange: 25.0,
    volume: 6666666,
    timestamp: Date.now(),
  },
  {
    id: "21",
    ticker: "BTN2",
    title: "Two Buttons",
    imageUrl: "/assets/memes/two buttons.jpg",
    price: 222.0,
    percentChange: 22.2,
    volume: 2222222,
    timestamp: Date.now(),
  },
  {
    id: "22",
    ticker: "CHUNG",
    title: "Big Chungus",
    imageUrl: "/assets/memes/big chungus.jpg",
    price: 333.0,
    percentChange: 33.3,
    volume: 3333333,
    timestamp: Date.now(),
  },
  {
    id: "23",
    ticker: "SALT",
    title: "Saltbae",
    imageUrl: "/assets/memes/saltbae.jpg",
    price: 123.45,
    percentChange: 23.45,
    volume: 5454545,
    timestamp: Date.now(),
  },
  {
    id: "24",
    ticker: "KAREN",
    title: "Karen",
    imageUrl: "/assets/memes/karen.jpg",
    price: 0.01,
    percentChange: -99.0,
    volume: 1010101,
    timestamp: Date.now(),
  },
  {
    id: "25",
    ticker: "GGG",
    title: "Good Guy Greg",
    imageUrl: "/assets/memes/good guy greg.jpg",
    price: 456.0,
    percentChange: 45.6,
    volume: 4564564,
    timestamp: Date.now(),
  },
  {
    id: "26",
    ticker: "OAG",
    title: "Overly Attached Girlfriend",
    imageUrl: "/assets/memes/overly attached girlfriend.jpg",
    price: 0.5,
    percentChange: -50.0,
    volume: 5050505,
    timestamp: Date.now(),
  },
  {
    id: "27",
    ticker: "CHOCO",
    title: "Chocolate Rain",
    imageUrl: "/assets/memes/chocolate rain.jpg",
    price: 24.99,
    percentChange: 2.49,
    volume: 2424242,
    timestamp: Date.now(),
  },
  {
    id: "28",
    ticker: "MORPH",
    title: "Morpheus",
    imageUrl: "/assets/memes/morpheus.jpg",
    price: 101.01,
    percentChange: 10.1,
    volume: 1010101,
    timestamp: Date.now(),
  },
  {
    id: "29",
    ticker: "LEROY",
    title: "Leroy Jenkins",
    imageUrl: "/assets/memes/leroy jenkins.jpg",
    price: 33.33,
    percentChange: 33.33,
    volume: 3333333,
    timestamp: Date.now(),
  },
  {
    id: "30",
    ticker: "PHILO",
    title: "Philosoraptor",
    imageUrl: "/assets/memes/philosoraptor.jpg",
    price: 42.42,
    percentChange: 4.24,
    volume: 4242424,
    timestamp: Date.now(),
  },
  {
    id: "31",
    ticker: "STEVE",
    title: "Scumbag Steve",
    imageUrl: "/assets/memes/scumbag steve.jpg",
    price: 6.66,
    percentChange: -66.6,
    volume: 6666666,
    timestamp: Date.now(),
  },
  {
    id: "32",
    ticker: "CHUCK",
    title: "Chuck Norris Facts",
    imageUrl: "/assets/memes/chuck norris facts.jpg",
    price: 9999.99,
    percentChange: 99.99,
    volume: 9999999,
    timestamp: Date.now(),
  },
  {
    id: "33",
    ticker: "DSTR",
    title: "Disaster Girl",
    imageUrl: "/assets/memes/Disaster_Girl.jpg",
    price: 66.6,
    percentChange: 66.6,
    volume: 6666666,
    timestamp: Date.now(),
  },
  {
    id: "34",
    ticker: "MATH",
    title: "Confused Math Lady",
    imageUrl: "/assets/memes/Confused Math Lady.jpg",
    price: 314.15,
    percentChange: 3.1415,
    volume: 3141592,
    timestamp: Date.now(),
  },
  {
    id: "35",
    ticker: "SKID",
    title: "Success Kid",
    imageUrl: "/assets/memes/Success Kid.jpg",
    price: 789.0,
    percentChange: 78.9,
    volume: 7890123,
    timestamp: Date.now(),
  },
  {
    id: "36",
    ticker: "KBCAT",
    title: "Keyboard Cat",
    imageUrl: "/assets/memes/Keyboard Cat.jpg",
    price: 88.0,
    percentChange: 8.8,
    volume: 8888888,
    timestamp: Date.now(),
  },
  {
    id: "37",
    ticker: "OVER9K",
    title: "Over 9000",
    imageUrl: "/assets/memes/Over 9000.jpg",
    price: 9001.0,
    percentChange: 90.01,
    volume: 9000100,
    timestamp: Date.now(),
  },
  {
    id: "38",
    ticker: "HARAMB",
    title: "Harambe",
    imageUrl: "/assets/memes/Harambe.jpg",
    price: 28.05,
    percentChange: 280.5,
    volume: 2805000,
    timestamp: Date.now(),
  },
  {
    id: "39",
    ticker: "BLB",
    title: "Bad Luck Bryan",
    imageUrl: "/assets/memes/bad luck bryan.jpg",
    price: 0.01,
    percentChange: -99.99,
    volume: 1337000,
    timestamp: Date.now(),
  },
  {
    id: "40",
    ticker: "BOROMIR",
    title: "One Does Not Simply",
    imageUrl: "/assets/memes/one does not simply.jpg",
    price: 111.11,
    percentChange: 11.11,
    volume: 1111111,
    timestamp: Date.now(),
  },
  {
    id: "41",
    ticker: "DANCE",
    title: "Dancing Baby",
    imageUrl: "/assets/memes/dancing baby.jpg",
    price: 25.0,
    percentChange: 2.5,
    volume: 2525252,
    timestamp: Date.now(),
  },
  {
    id: "42",
    ticker: "GRUMP",
    title: "Grumpy Cat",
    imageUrl: "/assets/memes/grumpy cat.jpg",
    price: 987.65,
    percentChange: -9.87,
    volume: 9876543,
    timestamp: Date.now(),
  },
  {
    id: "43",
    ticker: "NYAN",
    title: "Nyan Cat",
    imageUrl: "/assets/memes/nyan cat.jpg",
    price: 456.78,
    percentChange: 45.67,
    volume: 4567890,
    timestamp: Date.now(),
  },
  {
    id: "44",
    ticker: "RAGE",
    title: "Rage Comics",
    imageUrl: "/assets/memes/rage comics.jpg",
    price: 123.45,
    percentChange: 12.34,
    volume: 1234567,
    timestamp: Date.now(),
  },
  {
    id: "45",
    ticker: "LOLCAT",
    title: "Lolcats",
    imageUrl: "/assets/memes/lolcats.jpg",
    price: 567.89,
    percentChange: 56.78,
    volume: 5678901,
    timestamp: Date.now(),
  },
  {
    id: "46",
    ticker: "RICK",
    title: "Rick Roll",
    imageUrl: "/assets/memes/rick roll.jpg",
    price: 1987.09,
    percentChange: 19.87,
    volume: 1987000,
    timestamp: Date.now(),
  },
]
