import type { MemeTicker } from "./types"

export const initialMemes: MemeTicker[] = [
  {
    id: "1",
    ticker: "KEK",
    title: "Top Kek",
    imageUrl: "/assets/memes/trollface.jpg",
    price: 420.69,
    percentChange: 69.42,
    volume: 8008135,
    timestamp: Date.now(),
  },
  {
    id: "2",
    ticker: "LMAO",
    title: "Laughing My Assets Off",
    imageUrl: "/assets/memes/leonardo dicaprio laughing.jpg",
    price: 69.42,
    percentChange: -4.2,
    volume: 1337420,
    timestamp: Date.now(),
  },
  {
    id: "3",
    ticker: "NPC",
    title: "Non-Profitable Currency",
    imageUrl: "/assets/memes/wojak.jpg",
    price: 0.01,
    percentChange: 1000.0,
    volume: 9000001,
    timestamp: Date.now(),
  },
  {
    id: "4",
    ticker: "WOJAK",
    title: "Feels Bad Man",
    imageUrl: "/assets/memes/sad pablo.jpg",
    price: 0.5,
    percentChange: -99.9,
    volume: 1234567,
    timestamp: Date.now(),
  },
  {
    id: "5",
    ticker: "PEPE",
    title: "Rare Pepe Index",
    imageUrl: "/assets/memes/pepe the frog.jpg",
    price: 1337.0,
    percentChange: 13.37,
    volume: 4206969,
    timestamp: Date.now(),
  },
  {
    id: "6",
    ticker: "TENDIES",
    title: "Chicken Tendies",
    imageUrl: "/assets/memes/first world problems.jpg",
    price: 20.0,
    percentChange: 5.0,
    volume: 8675309,
    timestamp: Date.now(),
  },
  {
    id: "7",
    ticker: "CHAD",
    title: "Chad Investments",
    imageUrl: "/assets/memes/giga cahd.jpg",
    price: 999.99,
    percentChange: 42.0,
    volume: 6942069,
    timestamp: Date.now(),
  },
  {
    id: "8",
    ticker: "COOMER",
    title: "Coomer Capital",
    imageUrl: "/assets/memes/hide the pain harold.jpg",
    price: 34.95,
    percentChange: -2.5,
    volume: 5318008,
    timestamp: Date.now(),
  },
  {
    id: "9",
    ticker: "BOOBA",
    title: "Booba Ventures",
    imageUrl: "/assets/memes/surprised pikachu.jpg",
    price: 80.08,
    percentChange: 8.008,
    volume: 8008135,
    timestamp: Date.now(),
  },
  {
    id: "10",
    ticker: "DOGE",
    title: "Much Wow",
    imageUrl: "/assets/memes/doge.jpg",
    price: 0.42069,
    percentChange: -12.34,
    volume: 1234321,
    timestamp: Date.now(),
  },
  {
    id: "11",
    ticker: "ANON",
    title: "Anonymous Holdings",
    imageUrl: "/assets/memes/ancient aliens guy.jpg",
    price: 4.0,
    percentChange: 0.01,
    volume: 4004004,
    timestamp: Date.now(),
  },
  {
    id: "12",
    ticker: "WAGMI",
    title: "We're All Gonna Make It",
    imageUrl: "/assets/memes/stonks.jpg",
    price: 1000000.0,
    percentChange: 100.0,
    volume: 9999999,
    timestamp: Date.now(),
  },
]
